# Generated by Django 5.0 on 2023-12-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userNegrar',
        ),
    ]
