# Generated by Django 5.0 on 2023-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0003_coffee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='photo',
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
