# Generated by Django 5.0 on 2023-12-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0004_remove_coffee_photo_alter_coffee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='photo_dir',
            field=models.CharField(default='img/kawa1.png', max_length=255),
        ),
    ]
