# Generated by Django 5.0 on 2023-12-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0005_coffee_photo_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='photo_dir',
            field=models.CharField(default='{% static "img/kawa1.png" %}', max_length=255),
        ),
    ]
