# Generated by Django 5.0 on 2023-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0006_alter_coffee_photo_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='photo_dir',
        ),
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.CharField(default='path/to/default/image.jpg', max_length=255),
        ),
    ]
