# Generated by Django 5.0 on 2024-01-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0007_remove_coffee_photo_dir_coffee_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userNegrar',
        ),
    ]
