# Generated by Django 5.0 on 2024-01-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0008_delete_usernegrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('hour', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewhub.coffee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='brewhub.order')),
            ],
        ),
    ]
