# Generated by Django 5.0 on 2024-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0009_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tables', models.JSONField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
            ],
        ),
    ]
