# Generated by Django 5.0 on 2024-01-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0011_remove_reservation_id_user_reservation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
