# Generated by Django 5.0 on 2024-01-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0013_table_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_tables',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
