# Generated by Django 5.0 on 2024-01-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0014_remove_reservation_reserved_tables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_ids', models.JSONField()),
                ('selected_times', models.JSONField()),
                ('reservation_date', models.DateField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
    ]
