# Generated by Django 5.0 on 2024-01-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0015_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
