# Generated by Django 5.0 on 2024-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhub', '0017_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
